CREATE DATABASE todo_app;

USE todo_app;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20),
    email VARCHAR(50) UNIQUE,
    password VARCHAR(200),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

